version: '3'

services:
  leap-hand-ros1:
    build:
      context: .
      args:
        - ROS_VERSION=1
    image: leap-hand-ros1
    container_name: leap-hand-ros1
    privileged: true
    devices:
      - "/dev:/dev"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    command: bash -c "source /ros_entrypoint.sh && bash"
    
  leap-hand-ros2:
    build:
      context: .
      args:
        - ROS_VERSION=2
    image: leap-hand-ros2
    container_name: leap-hand-ros2
    privileged: true
    devices:
      - "/dev:/dev"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    command: bash -c "source /ros_entrypoint.sh && bash"

